DATASET:
  root_dataset: "./Look_into_Person_Dataset/"
  list_train: "./Look_into_Person_Dataset/train.odgt"
  list_val: "./Look_into_Person_Dataset/val.odgt"
  num_class: 20
  imgSizes: (150, 225, 300, 375, 450)
  imgMaxSize: 500
  padding_constant: 32
  segm_downsampling_rate: 4
  random_flip: True

MODEL:
  arch_encoder: "hrnetv2"
  arch_decoder: "c1"
  fc_dim: 720

TRAIN:
  batch_size_per_gpu: 2
  num_epoch: 30
  start_epoch: 0
  epoch_iters: 3807
  optim: "SGD"
  lr_encoder: 0.02
  lr_decoder: 0.02
  lr_pow: 0.9
  beta1: 0.9
  weight_decay: 1e-4
  deep_sup_scale: 0.4
  fix_bn: False
  workers: 16
  disp_iter: 20
  seed: 304

VAL:
  visualize: False
  checkpoint: "epoch_30.pth"

TEST:
  checkpoint: "epoch_30.pth"
  result: "./"

DIR: "ckpt/lip-full-hrnetv2-c1"
